### ISSUE TITLE
There is no suppress warnings key for this checker

### ISSUE THREAD

**Issue by kelloggm** [msridhar/returnsrecv-checker#5]
All checkers should define at least one suppress warnings key via the `@SuppressWarningsKeys` meta-annotation, which should appear on the `Checker` class. Can you add one to this checker, please?

**Comment by kelloggm** [comment]
Update: I've learned that there is a default suppress warning key for every checker, which is the name of the checker (in this case, `"returnsrcvr"`). If that's okay with you all, feel free to close this issue.

**Comment by msridhar** [comment]
I think I'm fine with the default.  Thanks for digging and finding out about the defaults @kelloggm.  I'm going to close this issue.
